### ISSUE TITLE
Rename env variables

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-media-service#23]
Please rename the used env variables:

```
  MEDIA_HOST
  MEDIA_PORT
  MEDIA_DATABASE_HOST
  MEDIA_DATABASE_PORT
  MEDIA_DATABASE_NAME
  MEDIA_DATABASE_USER
  MEDIA_DATABASE_PASSWORD
  MEDIA_DATABASE_TABLE
```

Using the MEDIA prefix makes it more easy to use all env variables of all services in a shared namespace. This is interesing to our generated YAML configuration and it is much easier for the admins to override them in special setup.

The defaults do not matter to me because I will set them all in the manage service.

@gsiv and @peb-adr : Do we want to prefix the other media env variables for caching etc. too?

**Comment by normanjaeckel** [comment]
Please also change and use the following:
```
  MEDIA_CACHE_SIZE: 10
  MEDIA_CACHE_DATA_MIN_SIZE_KB: 0
  MEDIA_CACHE_DATA_MAX_SIZE_KB: 10240
```

Open question: Is the var CHECK_REQUEST_URL still valid? In OpenSlides 3 this is an url to server:8000/check-media but I do not know whether this exists also in OpenSlides 4.

**Comment by gsiv** [comment]
I'm afraid you're looking at the `master` branch which is still for OpenSlides 3.  The version used by OpenSlides 4 is on the `openslides4-dev` branch, cf. the main repository's submodule.

Please have a look at the OpenSlides 4 branch and see if anything remains to be done there.

It may be about time to merge `openslides4-dev` back into `master`, though, especially since there are changes potentially missing from the OpenSlides 4 version.

**Comment by normanjaeckel** [comment]
The README in openslides4-dev branch tells me that the service still uses the "old" env vars. So this issue is also valid for OpenSlides4. All environment variables should be prefixed with MEDIA_ and follow the naming as mentioned above. This would be very nice and consistant to the respective scheme in the datastore e. g.
