### ISSUE TITLE
Move master -> stable/3.4.x and openslides4-dev -> master

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-media-service#26]
In addition to the main repo, this repo's main branch (master) should be moved to `stable/3.4.x` and the branch "openslides4-dev" should become the new `master`-branch.

**Comment by gsiv** [comment]
This might just be a simple matter of phrasing it but just to be clear, I believe you are going to need to merge the branches, not merely rename them.  There have been changes on `master` that have not been mirrored to `openslides4-dev` yet.

**Comment by jsangmeister** [comment]
This should really be done in the next time - we are diverging only more and more. @gsiv I think you have probably the best overview about the changes, can you do this?

**Comment by gsiv** [comment]
The only missing feature from the current stable branch appears to be the table/schema configuration.  Unfortunately, it is not transferable from the stable branch because of significant differences.  In particular, there are now two tables instead of one, making the existing concept unsuitable for OpenSlides 4.

I have added a new issue for this problem: https://github.com/OpenSlides/openslides-media-service/issues/39.  This issue can return to concentrating on merely *renaming* branches.

**Comment by jsangmeister** [comment]
done
