### ISSUE TITLE
Store database credentials in Docker secrets

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-media-service#27]
The service should, in my opinion, not receive `MEDIA_DATABASE_USER` and `MEDIA_DATABASE_PASSWORD` from the environment but read them from a Docker secret.

The current situation is especially bad because the [manage](https://github.com/OpenSlides/openslides-manage-service/) service's docker-compose.yml template includes the variables in its `x-default-environment` which means that the variables are made available to all services!

**Comment by normanjaeckel** [comment]
Please let the media service check the new env var `MEDIA_DATABASE_PASSWORD_FILE` and let it read the password from this file instead of checking `MEDIA_DATABASE_PASSWORD`.

The user is not affected.

**Comment by normanjaeckel** [comment]
In https://github.com/OpenSlides/openslides-manage-service/pull/ the defaults of some env vars in the manage service will change. In this repo the vars `MEDIA_DATABASE_PASSWORD_FILE` and `MEDIA_DATABASE_USER_FILE` is affected. (Maybe the user file var should removed, but this is another discussion, see OpenSlides/openslides-manage-service#116.) The new value is /run/secrets/postgres_password and not /run/secrets/media_postgres_password because in default setup there is only one postgres instance and password for all services (datastore, media and vote).

Please check if is is necessary or at least a good idea to change the defaults here or at least in dev setup to be more consistant.
