### ISSUE TITLE
Traceback on container exit

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-media-service#72]
``` python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 126, in run
    self.run_for_one(timeout)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 85, in run_for_one
    self.wait(timeout)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 37, in wait
    ret = select.select(self.wait_fds, [], [], timeout)
TypeError: exit expected at most 1 argument, got 3
```

I found that 94a25fc42839f6ac0af027ec0f146901c8256de5 adds some kind of new signal handling.
I'm not sure how this was needed. But [these lines](https://github.com/OpenSlides/openslides-media-service/blob/8d464bd55c7980108e1999940f3921ffffe00e4f/src/mediaserver.py#L137-L138C1) seem to introduce the problem.

`sys.exit` is set as handler for `SIGTERM` and `SIGINT`.
However is seems there was a missed detail. The handler will be called with two arguments ([source](https://docs.python.org/3/library/signal.html#signal.signal)).
@jsangmeister I guess an easy fix would be adding an (anonymus) function that ignores the the args and then calls `exit`. But I trust you can find the best suitable solution for this ;) .

**Comment by jsangmeister** [comment]
I don't think I understand the problem. As far as I see it, the line `signal(sig, partial(sys.exit, 0))` calls the `signal` function correctly with two args (the signal and the handler). The handler is `sys.exit(0)`, which is also correct and calls the `exit` function with one argument and not three. Or am I missing something?

The changes were needed because with docker does not delegate signals correctly with the alternative array call form, therefore the `exec` version is needed. It is also used, e.g., by the backend in https://github.com/OpenSlides/openslides-backend/blob/main/Dockerfile.
